name: ci-pre-pr
on:
  pull_request:
    types:
      - oepn
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo $GITHUB_CONTEXT